name: 🐛 Bug Report
description: Report a bug or unexpected behaviour in Loom Spinner
labels: [bug]
body:
  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: What version of Loom Spinner is this affecting?
      placeholder: e.g. 3.0.0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Operating System
      description: What OS are you running Loom Spinner on?
      placeholder: e.g. Ubuntu 24.04, macOS 15.0, Windows 11

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue
      placeholder: 1. Run `loom spin:up my-project`\n2. Visit https://example.app\n3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      placeholder: What did you expect to happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      placeholder: What actually happened?
