options:
  environment:
    php:
      version: 8.4
      xdebug: true
    node:
      version: 25
    server:
      enabled: true
    database:
      enabled: true
      driver: mysql
      rootPassword: docker